---
deployment:
  tasks:
    - DIRS=("public_html" "jack.haden-enneking.net" "jenny.haden-enneking.net")
    - for DIR in "${DIRS[@]}"; do printf "\n${DIR}\n"; /usr/bin/rsync -avv "./${DIR}/." "${HOME}/${DIR}/"; done
