---
deployment:
  tasks:
    - for DIRNAME in "public_html" "jack.haden-enneking.net" "jenny.haden-enneking.net"; do printf "\n${DIRNAME}\n"; /usr/bin/rsync -avv "./${DIRNAME}/." "${HOME}/${DIRNAME}/"; done
